### ISSUE TITLE
Crashes when selecting single player from menu

### ISSUE THREAD

**Issue by monreal** [diasurgical/devilutionX#107]
Game used to work some weeks ago for me on Fedora but now crashes when selecting single player in the menu:

```
DUMMY: SetUnhandledExceptionFilter @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:507
DUMMY: GetSystemInfo @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:573
DUMMY: CreateFileMappingA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:665
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: LoadIconA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:431
DUMMY: LoadCursorA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:446
DUMMY: LoadImageA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:440
DUMMY: RegisterClassExA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:399
DUMMY: UpdateWindow @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:382
DUMMY: UiAppActivate @ /home/micmon/code/gaming/devilutionX.git/SourceX/DiabloUI/diabloui.cpp:422
DUMMY: GetWindowLongA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:778
DUMMY: SetWindowLongA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:784
DUMMY: SDrawRealizePalette @ /home/micmon/code/gaming/devilutionX.git/SourceX/storm/storm.cpp:705
DUMMY: DefWindowProcA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:769
DUMMY: SetCooperativeLevel @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:98
DUMMY: SetDisplayMode @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:104
DUMMY: CreateSurface @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:55
DUMMY: CreatePalette @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:40
DUMMY: SetPalette @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:199
DUMMY: GdiSetBatchLimit @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:270
DUMMY: GetCaps @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:155
DUMMY: CreateSurface @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:55
DUMMY: SDrawManualInitialize @ /home/micmon/code/gaming/devilutionX.git/SourceX/storm/storm_dx.cpp:19
DUMMY: WaitForVerticalBlank @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:114
DUMMY: BltFast @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:134
DUMMY: Unlock @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/ddraw.cpp:205
DUMMY: sound_DirectSoundCreate @ /home/micmon/code/gaming/devilutionX.git/SourceX/sound.cpp:405
DUMMY: SVidInitialize @ /home/micmon/code/gaming/devilutionX.git/SourceX/storm/storm.cpp:424
DUMMY: GetFileVersionInfoSizeA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:167
DUMMY: GetFileVersionInfoA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:175
DUMMY: VerQueryValueA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:183
BasePath: /home/micmon/GAMES/diablo/
DUMMY: SFileSetBasePath @ /home/micmon/code/gaming/devilutionX.git/SourceX/storm/storm.cpp:699
BasePath: /home/micmon/GAMES/diablo/
DUMMY: SFileSetBasePath @ /home/micmon/code/gaming/devilutionX.git/SourceX/storm/storm.cpp:699
DUMMY: sound_CreateSoundBuffer @ /home/micmon/code/gaming/devilutionX.git/SourceX/sound.cpp:270
TTF_OpenFont: Couldn't open CharisSILB.ttf
DUMMY: InvalidateRect @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:373
DUMMY: UpdateWindow @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc.cpp:382
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x1100
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: DispatchMessageA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc_msg.cpp:284
DUMMY: false_avail : return false although event avaliable
DUMMY: false_avail : return false although event avaliable
DUMMY: PeekMessageA : unknown SDL message 0x302
DUMMY: false_avail : return false although event avaliable
DUMMY: PostMessageA @ /home/micmon/code/gaming/devilutionX.git/SourceX/miniwin/misc_msg.cpp:294
DUMMY: SDrawGetFrameWindow @ /home/micmon/code/gaming/devilutionX.git/SourceX/storm/storm.cpp:307
DUMMY: UiProfileGetString @ /home/micmon/code/gaming/devilutionX.git/SourceX/DiabloUI/diabloui.cpp:386
=================================================================
==19331==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf1d09b88 at pc 0xf7975b87 bp 0xffad7fa8 sp 0xffad7b78
READ of size 64 at 0xf1d09b88 thread T0
    #0 0xf7975b86  (/lib/libasan.so.5+0x9db86)
    #1 0x840fbb7  (/home/micmon/GAMES/diablo/devilutionx+0x840fbb7)
    #2 0x834da85  (/home/micmon/GAMES/diablo/devilutionx+0x834da85)
    #3 0x834e256  (/home/micmon/GAMES/diablo/devilutionx+0x834e256)
    #4 0x816b383  (/home/micmon/GAMES/diablo/devilutionx+0x816b383)
    #5 0x823f566  (/home/micmon/GAMES/diablo/devilutionx+0x823f566)
    #6 0x807afa9  (/home/micmon/GAMES/diablo/devilutionx+0x807afa9)
    #7 0x83071b4  (/home/micmon/GAMES/diablo/devilutionx+0x83071b4)
    #8 0x81785ca  (/home/micmon/GAMES/diablo/devilutionx+0x81785ca)
    #9 0x823f9b7  (/home/micmon/GAMES/diablo/devilutionx+0x823f9b7)
    #10 0x816f915  (/home/micmon/GAMES/diablo/devilutionx+0x816f915)
    #11 0x805a6db  (/home/micmon/GAMES/diablo/devilutionx+0x805a6db)
    #12 0xf723e8a8 in __libc_start_main (/lib/libc.so.6+0x1a8a8)
    #13 0x805b4b5  (/home/micmon/GAMES/diablo/devilutionx+0x805b4b5)

0xf1d09b88 is located 0 bytes to the right of 1288-byte region [0xf1d09680,0xf1d09b88)
allocated by thread T0 here:
    #0 0xf79ec117 in __interceptor_malloc (/lib/libasan.so.5+0x114117)
    #1 0x81c9fe5  (/home/micmon/GAMES/diablo/devilutionx+0x81c9fe5)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib/libasan.so.5+0x9db86) 
Shadow bytes around the buggy address:
  0x3e3a1320: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e3a1330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e3a1340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e3a1350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e3a1360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x3e3a1370: 00[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e3a1380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e3a1390: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e3a13a0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e3a13b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e3a13c0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
=================================================================
==19331==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf1d09b88 at pc 0xf7975cb7 bp 0xffad7fa8 sp 0xffad7b78
WRITE of size 64 at 0xf1d09b88 thread T0
    #0 0xf7975cb6  (/lib/libasan.so.5+0x9dcb6)
    #1 0x840fc82  (/home/micmon/GAMES/diablo/devilutionx+0x840fc82)
    #2 0x834da85  (/home/micmon/GAMES/diablo/devilutionx+0x834da85)
    #3 0x834e256  (/home/micmon/GAMES/diablo/devilutionx+0x834e256)
    #4 0x816b383  (/home/micmon/GAMES/diablo/devilutionx+0x816b383)
    #5 0x823f566  (/home/micmon/GAMES/diablo/devilutionx+0x823f566)
    #6 0x807afa9  (/home/micmon/GAMES/diablo/devilutionx+0x807afa9)
    #7 0x83071b4  (/home/micmon/GAMES/diablo/devilutionx+0x83071b4)
    #8 0x81785ca  (/home/micmon/GAMES/diablo/devilutionx+0x81785ca)
    #9 0x823f9b7  (/home/micmon/GAMES/diablo/devilutionx+0x823f9b7)
    #10 0x816f915  (/home/micmon/GAMES/diablo/devilutionx+0x816f915)
    #11 0x805a6db  (/home/micmon/GAMES/diablo/devilutionx+0x805a6db)
    #12 0xf723e8a8 in __libc_start_main (/lib/libc.so.6+0x1a8a8)
    #13 0x805b4b5  (/home/micmon/GAMES/diablo/devilutionx+0x805b4b5)

0xf1d09b88 is located 0 bytes to the right of 1288-byte region [0xf1d09680,0xf1d09b88)
allocated by thread T0 here:
    #0 0xf79ec117 in __interceptor_malloc (/lib/libasan.so.5+0x114117)
    #1 0x81c9fe5  (/home/micmon/GAMES/diablo/devilutionx+0x81c9fe5)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib/libasan.so.5+0x9dcb6) 
Shadow bytes around the buggy address:
  0x3e3a1320: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e3a1330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e3a1340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e3a1350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e3a1360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x3e3a1370: 00[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e3a1380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e3a1390: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e3a13a0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e3a13b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e3a13c0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
AddressSanitizer:DEADLYSIGNAL
=================================================================
==19331==ERROR: AddressSanitizer: SEGV on unknown address 0xf1e00000 (pc 0xf72a870a bp 0xffad7fa8 sp 0xffad7b28 T0)
==19331==The signal is caused by a READ memory access.
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

**Comment by AJenbo** [comment]
what commit is this for?

**Comment by monreal** [comment]
1066c4928141ee64a88849d7aae62f9518bb1050

**Comment by monreal** [comment]
32 bit build

**Comment by AJenbo** [comment]
Unfortunately, the crash log doesn't give much information in this case, and I am unable to replicate it on Ubuntu 19.04. Could you try and bisect the issue to locate the offending commit. Suggested commits to try: 0c4b4719b88d7b226eaca2a9fa2cb1ef22e971cd 01a392900a63715f329d0599bc0d2fa03a862def 350db82e4aae8d3d1e3f5daf74c13ae027835fea

**Comment by AJenbo** [comment]
Looks like the issue could potentially have been down to unititialized data, please also try the latest commit.

**Comment by monreal** [comment]
> Looks like the issue could potentially have been down to unititialized data, please also try the latest commit.

Latest head still shows the same problem... will try to bisect tomorrow

**Comment by monreal** [comment]
I tried multiple revisions around the time I last played (savegame was mid march) and I am not able to get a working build now. Thinking again now I did update my system from Fedora 29 to 30 in the meantime. Maybe some new gcc compiler feature is causing this now?

**Comment by iSiek** [comment]
> BasePath: /home/micmon/GAMES/diablo/

This is the same case as I repored in [#126](https://github.com/diasurgical/devilutionX/issues/126) It is based on converting system path to lower characters. In my case that was related with home directory, this time it is about "GAMES" folder in the path.

I thing this has been already solved as per my request.

Regards,
Krzysztof

**Comment by monreal** [comment]
Yeah, seems to work again. Thanks for the heads up
