### ISSUE TITLE
OOB error in AddFlash when cast by shrine

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1500]
**To Reproduce**
1. Play Hellfire
2. Find a Sparkling Shrine
3. Use it

**Additional context**
```
/home/ajenbo/code/diablo/devilutionX/Source/missiles.cpp:2518:34: runtime error: index -1 out of bounds for type 'MonsterStruct [200]'
=================================================================
==25143==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55eebcb5414c at pc 0x55eebb172823 bp 0x7fffbaa90c40 sp 0x7fffbaa90c30
READ of size 1 at 0x55eebcb5414c thread T0
    #0 0x55eebb172822 in devilution::AddFlash(int, int, int, int, int, int, signed char, int, int) /home/ajenbo/code/diablo/devilutionX/Source/missiles.cpp:2518
    #1 0x55eebb1a3ef4 in devilution::AddMissile(int, int, int, int, int, int, signed char, int, int, int) /home/ajenbo/code/diablo/devilutionX/Source/missiles.cpp:3426
    #2 0x55eebb40715b in devilution::OperateShrineSparkling(int, int, int) /home/ajenbo/code/diablo/devilutionX/Source/objects.cpp:4232
    #3 0x55eebb40a365 in devilution::OperateShrine(int, int, devilution::_sfx_id) /home/ajenbo/code/diablo/devilutionX/Source/objects.cpp:4486
```

**Comment by AJenbo** [comment]
The offending code:

```cpp
		missile[mi]._midam = monster[id].mLevel << 1;
```

This will cause flash to do some completely random amount of damage. Instead, it should be current dungeon level / 2.
