### ISSUE TITLE
Android crash on start 

### ISSUE THREAD

**Issue by licaon-kter** [diasurgical/devilutionX#3017]
```
FATAL EXCEPTION: SDLActivity
Process: org.diasurgical.devilutionx, PID: 2606
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.SurfaceHolder android.view.SurfaceView.getHolder()' on a null object reference
	at org.diasurgical.devilutionx.DevilutionXSDLActivity$1.onGlobalLayout(DevilutionXSDLActivity.java:65)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2987)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1950)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8186)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:811)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
``` 

Self build via fdroidserver, 83b45d6c942a86f88934e0886bd8411409d78aca AOSP 11, `devilutionx.mpq` generated by the build process

Also seen with 9f7c69f4f5027cecc7516bc8916c4dc58af5ddd2 earlier

**Comment by AJenbo** [comment]
What sort of device? Does it have hardware acceleration?

**Comment by licaon-kter** [comment]
Last working build that I have is 60b1351ed7bafb0c0dc9fcc650c85925338c9b57 

[SD855](https://www.notebookcheck.net/Qualcomm-Snapdragon-855-SoC-Benchmarks-and-Specs.375436.0.html) powered device, should have enough power :)

**Comment by licaon-kter** [comment]
Looking in ADB and in the actual APKs, I'm missing `libfreetype.so` and `libSDL2_ttf.so` in the crashing builds.

**Comment by AJenbo** [comment]
> Looking in ADB and in the actual APKs, I'm missing `libfreetype.so` and `libSDL2_ttf.so` in the crashing builds, for all 4 arches.

We nol onger depend on libfreetype or SDL2_ttf, probably the java code is still set to try and load them.

**Comment by AJenbo** [comment]
@licaon-kter could you see if this fixes it: https://github.com/diasurgical/devilutionX/pull/3018

**Comment by licaon-kter** [comment]
@AJenbo Yup,thanks

**Comment by julealgon** [comment]
> > /LE:
> 
> ???

Seems to be "Later Edit" 😛

**Comment by licaon-kter** [comment]
@julealgon yes, shorthand :)
