### ISSUE TITLE
Error at launch on Manjaro

### ISSUE THREAD

**Issue by hamdyaea** [diasurgical/devilutionX#368]
This my error message when I run the game : 

```
SFileOpenFile: Not found: ui_art\title.pcx
TTF_OpenFont: Couldn't open CharisSILB.ttf
SFileOpenFile: Not found: ui_art\black.pcx
AddressSanitizer:DEADLYSIGNAL
=================================================================
==23356==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7fd8fdbb7ef9 bp 0x000000000000 sp 0x7ffc6cb5b420 T0)
==23356==The signal is caused by a READ memory access.
==23356==Hint: address points to the zero page.
    #0 0x7fd8fdbb7ef8  (/usr/lib/libSDL2_ttf-2.0.so.0+0x2ef8)
    #1 0x55af94b828f6 in dvl::RenderUTF8_Solid_Wrapped(_TTF_Font*, char const*, SDL_Color, unsigned int, dvl::TextAlignment) /home/hamdy/Documents/devilutionX/SourceX/DiabloUI/ttf_render_wrapped.cpp:30
    #2 0x55af94b7fc1e in dvl::DrawTTF(char const*, SDL_Rect const&, int, SDL_Color const&, SDL_Color const&, dvl::TtfSurfaceCache**) /home/hamdy/Documents/devilutionX/SourceX/DiabloUI/text_draw.cpp:42
    #3 0x55af94b7112c in Render /home/hamdy/Documents/devilutionX/SourceX/DiabloUI/diabloui.cpp:548
    #4 0x55af94b7303c in RenderItem /home/hamdy/Documents/devilutionX/SourceX/DiabloUI/diabloui.cpp:640
    #5 0x55af94b74d9a in dvl::UiRenderItems(dvl::UiItem*, unsigned long) /home/hamdy/Documents/devilutionX/SourceX/DiabloUI/diabloui.cpp:759
    #6 0x55af94b79468 in DialogLoop /home/hamdy/Documents/devilutionX/SourceX/DiabloUI/dialogs.cpp:286
    #7 0x55af94b79654 in dvl::UiOkDialog(char const*, char const*, bool, dvl::UiItem*, unsigned long) /home/hamdy/Documents/devilutionX/SourceX/DiabloUI/dialogs.cpp:310
    #8 0x55af94b79714 in dvl::UiErrorOkDialog(char const*, char const*, bool) /home/hamdy/Documents/devilutionX/SourceX/DiabloUI/dialogs.cpp:322
    #9 0x55af94c081b8 in dvl::InsertCDDlg(char const*) /home/hamdy/Documents/devilutionX/Source/appfat.cpp:120
    #10 0x55af94d40cd9 in dvl::init_archives() /home/hamdy/Documents/devilutionX/Source/init.cpp:77
    #11 0x55af94c08d5e in dvl::diablo_init(char*) /home/hamdy/Documents/devilutionX/Source/diablo.cpp:237
    #12 0x55af94c08e34 in dvl::WinMain(void*, void*, char*, int) /home/hamdy/Documents/devilutionX/Source/diablo.cpp:275
    #13 0x55af94b846d9 in main /home/hamdy/Documents/devilutionX/SourceX/main.cpp:28
    #14 0x7fd8fcbc6152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
    #15 0x55af94ab062d in _start (/home/hamdy/Documents/devilutionX/build/devilutionx+0xd9e62d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/libSDL2_ttf-2.0.so.0+0x2ef8) 
==23356==ABORTING

```

**Comment by AJenbo** [comment]
Did you compile it yourself? Did you remember to copy the font and mpq to your install folder?

**Comment by glebm** [comment]
We shouldn't attempt to use the font if it's null (missing font is better than segfault)

**Comment by hamdyaea** [comment]
Yes I have compiled myself on Manjaro.  SDL2, sdl2 ttf and sdl2 mixer are installed. Do i need something else ?

**Comment by qndel** [comment]
"Did you remember to copy the font and mpq to your install folder?"

**Comment by hamdyaea** [comment]
I have just copy the diabdat.mpq file. Tell me the fonts I have to put the install folder please.

**Comment by qndel** [comment]
TTF_OpenFont: Couldn't open CharisSILB.ttf ...

**Comment by hamdyaea** [comment]
So it solved, the game is running. I copied the font from internet and put it in the build directory with the diabdat.mpq

**Comment by AJenbo** [comment]
The font is located in Packaging/resources, and is included with all releases.
