### ISSUE TITLE
Multiplayer game crashes on killing diablo

### ISSUE THREAD

**Issue by majek** [diasurgical/devilutionX#665]
When diablo is killed, multiplayer guests are kicked out okay (I think). Multiplayer server crashes with this traceback (tcp_server::handle_accept) after the cinematics

(compiled roughly from head 82845004cc89b2178b1f770448c9a2e50d81d34e )
```
terminate called after throwing an instance of 'std::system_error'
  what():  set_option: Bad file descriptor

Thread 1 "devilutionx" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff676b801 in __GI_abort () at abort.c:79
#2  0x00007ffff737d957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7383ae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7383b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7383d54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000000000042a398 in void asio::basic_socket<asio::ip::tcp>::set_option<asio::detail::socket_option::boolean<6, 1> >(asio::detail::socket_option::boolean<6, 1> const&) ()
#7  0x00000000004322a6 in dvl::net::tcp_server::handle_accept(std::shared_ptr<dvl::net::tcp_server::client_connection>, std::error_code const&) ()
#8  0x0000000000434c39 in void asio::asio_handler_invoke<asio::detail::binder1<std::_Bind<void (dvl::net::tcp_server::*(dvl::net::tcp_server*, std::shared_ptr<dvl::net::tcp_server::client_connection>, std::_Placeholder<1>))(std::shared_ptr<dvl::net::tcp_server::client_connection>, std::error_code const&)>, std::error_code> >(asio::detail::binder1<std::_Bind<void (dvl::net::tcp_server::*(dvl::net::tcp_server*, std::shared_ptr<dvl::net::tcp_server::client_connection>, std::_Placeholder<1>))(std::shared_ptr<dvl::net::tcp_server::client_connection>, std::error_code const&)>, std::error_code>&, ...) ()
#9  0x0000000000434900 in asio::detail::reactive_socket_accept_op<asio::basic_socket<asio::ip::tcp>, asio::ip::tcp, std::_Bind<void (dvl::net::tcp_server::*(dvl::net::tcp_server*, std::shared_ptr<dvl::net::tcp_server::client_connection>, std::_Placeholder<1>))(std::shared_ptr<dvl::net::tcp_server::client_connection>, std::error_code const&)> >::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned long) ()
#10 0x000000000042ae1e in dvl::net::tcp_client::poll() ()
#11 0x000000000042b869 in dvl::net::tcp_client::SNetLeaveGame(int) ()
#12 0x00000000004d4e2e in NetClose ()
#13 0x000000000044a9cf in StartGame ()
#14 0x00000000004a2641 in mainmenu_loop ()
#15 0x000000000044e668 in DiabloMain ()
#16 0x00007ffff674cb97 in __libc_start_main (main=0x4298f0 <main>, argc=1, argv=0x7fffffffde68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde58)
    at ../csu/libc-start.c:310
#17 0x0000000000408a8a in _start ()
```

**Comment by AJenbo** [comment]
I belive this has been solved.
